version: '3'
services:
  frontend:
    build:
      context: ./eatery-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend